### ISSUE TITLE
Is this gem available on ruby gems?

### ISSUE THREAD

**Issue by chrisbarber86** [combinaut/minibars#9]
https://rubygems.org/gems/minibars looks to only have an alpha version present?

v0.2.0 looks to be the current version in `master`

**Comment by jmhooper** [comment]
Are there any updates here? I am trying to use this in a project and would love to see the latest/greatest on rubygems instead of having to use a GitHub source.

**Comment by njakobsen** [comment]
Just released v0.2.0 as a gem.
